service: app
runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /bower_components
    static_dir: bower_components
    secure: always

  - url: /scripts/(.+)
    static_files: dist/scripts/\1
    upload: dist/scripts/(.+)
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /styles/(.+)
    static_files: dist/styles/\1
    upload: dist/styles/(.+)
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /fonts/(.+)
    static_files: dist/fonts/\1
    upload: dist/fonts/(.+)
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /images
    static_dir: images
    secure: always

  - url: /service-worker.js
    static_files: service-worker.js
    upload: service-worker.js
    secure: always

  - url: /manifest.json
    static_files: manifest.json
    upload: manifest.json
    secure: always

  - url: /.*
    static_files: index.html
    upload: index.html
    secure: always
    http_headers:
      strict-transport-security: max-age=15552000; preload
      link: '</bower_components/webcomponentsjs/webcomponents-lite.min.js>; rel=preload; as=script, </elements/elements.html>; rel=preload; </styles/coduno.css>; rel=preload; as=style, </styles/main.css>; rel=preload; as=style, </scripts/util.js>; rel=preload; as=script, </images/logo.svg>; rel=preload; as=image, </fonts/fonts.css>; rel=preload; as=style'
