module: app
runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /bower_components/(.+)
    static_files: bower_components/\1
    upload: bower_components/(.+)
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /
    static_files: app/index.html
    upload: app/index.html
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /(.+)
    static_files: app/\1
    upload: app/(.+)
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000
